/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularis;

import java.awt.BorderLayout;
import java.awt.datatransfer.DataFlavor;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.net.Socket;
import javax.swing.ImageIcon;
import javax.swing.text.AbstractDocument;


/**
 *
 * @author Lluís Barbó
 */
public class AdministracioForm extends javax.swing.JFrame {

    static int id;
    static String usuari;
    static String pass;
    static DataInputStream in;
    static DataOutputStream out;

    public static int getId() {
        return id;
    }

    public static void setId(int id) {
        AdministracioForm.id = id;
    }

    public static String getUsuari() {
        return usuari;
    }

    public static void setUsuari(String usuari) {
        AdministracioForm.usuari = usuari;
    }

    public static String getPass() {
        return pass;
    }

    public static void setPass(String pass) {
        AdministracioForm.pass = pass;
    }

    /**
     * Creates new form ClientForm
     */
    public AdministracioForm(DataInputStream in, DataOutputStream out) {
        this.in = in;
        this.out = out;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../images/logo.png")).getImage());
        setLocationRelativeTo(this);
        
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_show = new javax.swing.JPanel();
        jPanel_adm_form = new javax.swing.JPanel();
        jLabelLogOut = new javax.swing.JLabel();
        jLabelManagement = new javax.swing.JLabel();
        jLabelQueries = new javax.swing.JLabel();
        jLabelHelp = new javax.swing.JLabel();
        jLabelTools1 = new javax.swing.JLabel();
        jPanelPrin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRATION");
        setSize(new java.awt.Dimension(640, 480));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel_show.setBackground(new java.awt.Color(144, 164, 174));

        jPanel_adm_form.setBackground(new java.awt.Color(102, 102, 102));

        jLabelLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/logout-rounded-left-48.png"))); // NOI18N
        jLabelLogOut.setText("LogOut");
        jLabelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelLogOutMousePressed(evt);
            }
        });

        jLabelManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/home-48.png"))); // NOI18N
        jLabelManagement.setText("Management");
        jLabelManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelManagementMouseClicked(evt);
            }
        });

        jLabelQueries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/resume-48.png"))); // NOI18N
        jLabelQueries.setText("Queries");
        jLabelQueries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelQueriesMouseClicked(evt);
            }
        });

        jLabelHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/help-48.png"))); // NOI18N
        jLabelHelp.setText("Help");
        jLabelHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHelpMouseClicked(evt);
            }
        });

        jLabelTools1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/tools-48.png"))); // NOI18N
        jLabelTools1.setText("Tools");
        jLabelTools1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTools1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_adm_formLayout = new javax.swing.GroupLayout(jPanel_adm_form);
        jPanel_adm_form.setLayout(jPanel_adm_formLayout);
        jPanel_adm_formLayout.setHorizontalGroup(
            jPanel_adm_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_adm_formLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelManagement)
                .addGap(82, 82, 82)
                .addComponent(jLabelQueries)
                .addGap(103, 103, 103)
                .addComponent(jLabelTools1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabelHelp)
                .addGap(89, 89, 89)
                .addComponent(jLabelLogOut)
                .addGap(22, 22, 22))
        );
        jPanel_adm_formLayout.setVerticalGroup(
            jPanel_adm_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_adm_formLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel_adm_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQueries)
                    .addComponent(jLabelManagement)
                    .addComponent(jLabelTools1)
                    .addComponent(jLabelHelp)
                    .addComponent(jLabelLogOut))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelPrin.setBackground(new java.awt.Color(144, 164, 174));

        javax.swing.GroupLayout jPanelPrinLayout = new javax.swing.GroupLayout(jPanelPrin);
        jPanelPrin.setLayout(jPanelPrinLayout);
        jPanelPrinLayout.setHorizontalGroup(
            jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelPrinLayout.setVerticalGroup(
            jPanelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_showLayout = new javax.swing.GroupLayout(jPanel_show);
        jPanel_show.setLayout(jPanel_showLayout);
        jPanel_showLayout.setHorizontalGroup(
            jPanel_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_adm_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPrin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_showLayout.setVerticalGroup(
            jPanel_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_showLayout.createSequentialGroup()
                .addComponent(jPanel_adm_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseClicked

        LoginForm form = new LoginForm();
        form.setVisible(true);
        logOut(in, out);
        try {
            out.writeBoolean(true);
        } catch (IOException ex) {
            Logger.getLogger(AdministracioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jLabelLogOutMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        /*
        LoginForm form = new LoginForm();
        form.setVisible(true);
        logOut(in, out);
        try {
            out.writeBoolean(true);
        } catch (IOException ex) {
            Logger.getLogger(AdministracioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        
        */
        logOut(in, out);
        try {
            out.writeBoolean(true);
        } catch (Exception ex) {
            Logger.getLogger(AdministracioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.exit(0);
    }//GEN-LAST:event_formMouseClicked

    private void jLabelManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelManagementMouseClicked
        PanelManagement panelManagement = new PanelManagement();
        panelManagement.setSize(912,650);
        panelManagement.setLocation(0, 0);
        
        jPanelPrin.removeAll();
        jPanelPrin.add(panelManagement, BorderLayout.CENTER);
        jPanelPrin.revalidate();
        jPanelPrin.repaint();
        
    }//GEN-LAST:event_jLabelManagementMouseClicked

    private void jLabelQueriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQueriesMouseClicked
        PanelQueries panelQueries = new PanelQueries();
        panelQueries.setSize(912,650);
        panelQueries.setLocation(0, 0);
        
        jPanelPrin.removeAll();
        jPanelPrin.add(panelQueries, BorderLayout.CENTER);
        jPanelPrin.revalidate();
        jPanelPrin.repaint();
    }//GEN-LAST:event_jLabelQueriesMouseClicked

    private void jLabelHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHelpMouseClicked
        PanelHelp panelHelp = new PanelHelp();
        panelHelp.setSize(900,621);
        panelHelp.setLocation(0, 0);
        
        jPanelPrin.removeAll();
        jPanelPrin.add(panelHelp, BorderLayout.CENTER);
        jPanelPrin.revalidate();
        jPanelPrin.repaint();
    }//GEN-LAST:event_jLabelHelpMouseClicked

    private void jLabelTools1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTools1MouseClicked
        PanelTools panelTools = new PanelTools();
        panelTools.setSize(912,650);
        panelTools.setLocation(0, 0);
        
        jPanelPrin.removeAll();
        jPanelPrin.add(panelTools, BorderLayout.CENTER);
        jPanelPrin.revalidate();
        jPanelPrin.repaint();
    }//GEN-LAST:event_jLabelTools1MouseClicked

    private void jLabelLogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelLogOutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracioForm(in, out).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelHelp;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelManagement;
    private javax.swing.JLabel jLabelQueries;
    private javax.swing.JLabel jLabelTools1;
    private javax.swing.JPanel jPanelPrin;
    private javax.swing.JPanel jPanel_adm_form;
    private javax.swing.JPanel jPanel_show;
    // End of variables declaration//GEN-END:variables

    private void logOut(DataInputStream in, DataOutputStream out) {
        
        try {

            // Llegir la resposta del servidor al establir la connexió
            String resposta_svr = in.readUTF();
            //Enviem resposta al servidor amb el usuari i la contrasenya
            out.writeUTF("LOGIN," + getUsuari() + "," + getPass() + "," + getId());
            //Executo la consulta de la crida per sortir
            out.writeUTF("USER_EXIT");
            System.out.println("Valor getId: " + getId());

        } catch (IOException ex) {
            Logger.getLogger(AdministracioForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        /*
        Socket sc;
        try {
            sc = new Socket("127.0.0.1", 8000);
            DataInputStream in = new DataInputStream(sc.getInputStream());
            DataOutputStream out = new DataOutputStream(sc.getOutputStream());

            // Llegir la resposta del servidor al establir la connexió
            String resposta_svr = in.readUTF();
            //Enviem resposta al servidor amb el usuari i la contrasenya
            out.writeUTF("LOGIN," + getUsuari() + "," + getPass() + "," + getId());
            //Executo la consulta de la crida per sortir
            out.writeUTF("USER_EXIT");
            System.out.println("Valor getId: " + getId());

        } catch (IOException ex) {
            Logger.getLogger(AdministracioForm.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }
}
