/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularis;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utils.ManagedUsers;

/**
 *
 * @author Lluís Barbó
 */
public class frmhelp extends javax.swing.JInternalFrame {

    /**
     * Creates new formHelp
     */
    DataInputStream in;
    DataOutputStream out;
//    Socket cli;
//    int rol;
//    int access = 0;

    frmhelp(DataInputStream in, DataOutputStream out, int rol) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public frmhelp(DataInputStream in, DataOutputStream out) {
        initComponents();
        this.in = in;
        this.out = out;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        btnDonloadAdm = new javax.swing.JButton();
        btnDownloadRec = new javax.swing.JButton();
        jLabelName1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(144, 164, 174));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Download manuals"));

        jLabelName.setText("Manual Administration:");

        btnDonloadAdm.setBackground(new java.awt.Color(51, 51, 51));
        btnDonloadAdm.setForeground(new java.awt.Color(255, 255, 255));
        btnDonloadAdm.setText("Download");
        btnDonloadAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonloadAdmActionPerformed(evt);
            }
        });

        btnDownloadRec.setBackground(new java.awt.Color(51, 51, 51));
        btnDownloadRec.setForeground(new java.awt.Color(255, 255, 255));
        btnDownloadRec.setText("Download");
        btnDownloadRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDownloadRecMouseClicked(evt);
            }
        });
        btnDownloadRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadRecActionPerformed(evt);
            }
        });

        jLabelName1.setText("Manual Reception:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDownloadRec))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addGap(88, 88, 88)
                        .addComponent(btnDonloadAdm)))
                .addGap(0, 131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(btnDonloadAdm))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName1)
                    .addComponent(btnDownloadRec))
                .addContainerGap(353, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manuals");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonloadAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonloadAdmActionPerformed
        
        try {
            
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "src\\documents\\Document_Administrator.pdf");
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Check file details");
            
        }
    }//GEN-LAST:event_btnDonloadAdmActionPerformed

    private void btnDownloadRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadRecActionPerformed

        try {
            
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "src\\documents\\Document_Reception.pdf");
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Check file details");
            
        }
    }//GEN-LAST:event_btnDownloadRecActionPerformed


    private void btnDownloadRecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDownloadRecMouseClicked


    }//GEN-LAST:event_btnDownloadRecMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonloadAdm;
    private javax.swing.JButton btnDownloadRec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
