/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularis;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dapau69
 */
public class frmInici extends javax.swing.JFrame {

    static int id;
    static String usuari;
    static String pass;
    static DataInputStream in;
    static DataOutputStream out;
    static int rol;

    public static int getRol() {
        return rol;
    }

    public static void setRol(int rol) {
        frmInici.rol = rol;
    }

    public static DataInputStream getIn() {
        return in;
    }

    public static void setIn(DataInputStream in) {
        frmInici.in = in;
    }

    public static DataOutputStream getOut() {
        return out;
    }

    public static void setOut(DataOutputStream out) {
        frmInici.out = out;
    }

    public static int getId() {
        return id;
    }

    public static void setId(int id) {
        frmInici.id = id;
    }

    public static String getUsuari() {
        return usuari;
    }

    public static void setUsuari(String usuari) {
        frmInici.usuari = usuari;
    }

    public static String getPass() {
        return pass;
    }

    public static void setPass(String pass) {
        frmInici.pass = pass;
    }

    /**
     * Creates new form frmInici
     */
    public frmInici(DataInputStream in, DataOutputStream out, int rol) {
        this.in = in;
        this.out = out;
        this.rol = rol;
        initComponents();
        this.setExtendedState(frmInici.MAXIMIZED_BOTH);
        this.setTitle("Room Reservation System and Sales Management");
        setIconImage(new ImageIcon(getClass().getResource("../images/logoDDL.jpeg")).getImage());
        setLocationRelativeTo(this);
        switch (rol) {
            case 1:
                //Administrator
                JOptionPane.showMessageDialog(this, "You are logged in with the Administrator role");
                menuBaixa.setVisible(true);
                menuLogout.setVisible(true);
                menuHelp.setVisible(true);
                menuTools.setVisible(true);
                menuQueries.setVisible(true);
                menuReserves.setVisible(true);
                menuManagement.setVisible(true);
                break;
            case 2:
                //Reception
                JOptionPane.showMessageDialog(this, "You are logged in with the Reception role");
                menuBaixa.setVisible(false);
                menuLogout.setVisible(true);
                menuHelp.setVisible(true);
                menuTools.setVisible(false);
                menuQueries.setVisible(false);
                menuReserves.setVisible(true);
                menuManagement.setVisible(true);
                break;
            default:
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuManagement = new javax.swing.JMenu();
        menuItemRoom = new javax.swing.JMenuItem();
        menuItemServices = new javax.swing.JMenuItem();
        menuReserves = new javax.swing.JMenu();
        menuItemReser = new javax.swing.JMenuItem();
        menuItemClients = new javax.swing.JMenuItem();
        menuItemPayments = new javax.swing.JMenuItem();
        menuQueries = new javax.swing.JMenu();
        menuTools = new javax.swing.JMenu();
        jMenuItemUsers = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();
        menuItemHelp = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();
        menuBaixa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(144, 164, 174));

        menuBar.setBackground(new java.awt.Color(102, 102, 102));

        menuManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/home-48.png"))); // NOI18N
        menuManagement.setMnemonic('f');
        menuManagement.setText("Management");

        menuItemRoom.setMnemonic('o');
        menuItemRoom.setText("Rooms");
        menuManagement.add(menuItemRoom);

        menuItemServices.setMnemonic('s');
        menuItemServices.setText("Services");
        menuManagement.add(menuItemServices);

        menuBar.add(menuManagement);

        menuReserves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/reserve-48.png"))); // NOI18N
        menuReserves.setMnemonic('e');
        menuReserves.setText("Reseves");

        menuItemReser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReser.setMnemonic('t');
        menuItemReser.setText("Reservations and services");
        menuItemReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReserActionPerformed(evt);
            }
        });
        menuReserves.add(menuItemReser);

        menuItemClients.setMnemonic('y');
        menuItemClients.setText("Clients");
        menuItemClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientsActionPerformed(evt);
            }
        });
        menuReserves.add(menuItemClients);

        menuItemPayments.setMnemonic('p');
        menuItemPayments.setText("Payments");
        menuReserves.add(menuItemPayments);

        menuBar.add(menuReserves);

        menuQueries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/resume-48.png"))); // NOI18N
        menuQueries.setMnemonic('h');
        menuQueries.setText("Queries");
        menuBar.add(menuQueries);

        menuTools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/tools-48.png"))); // NOI18N
        menuTools.setText("Tools");
        menuTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuToolsActionPerformed(evt);
            }
        });

        jMenuItemUsers.setText("Users and access");
        jMenuItemUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemUsersMouseClicked(evt);
            }
        });
        jMenuItemUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsersActionPerformed(evt);
            }
        });
        menuTools.add(jMenuItemUsers);

        menuBar.add(menuTools);

        menuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/help-48.png"))); // NOI18N
        menuHelp.setText("Help");

        menuItemAbout.setText("About");
        menuHelp.add(menuItemAbout);

        menuItemHelp.setText("Help");
        menuHelp.add(menuItemHelp);

        menuBar.add(menuHelp);

        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/logout-rounded-left-48.png"))); // NOI18N
        menuLogout.setText("LogOut");
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        menuBar.add(menuLogout);

        menuBaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/password-key-24.png"))); // NOI18N
        menuBaixa.setText("Baixa");
        menuBaixa.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images_1_.png"))); // NOI18N
        menuBaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBaixaMouseClicked(evt);
            }
        });
        menuBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBaixaActionPerformed(evt);
            }
        });
        menuBar.add(menuBaixa);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        frmlogin form = new frmlogin();
        form.setVisible(true);
        logOut(in, out);
        this.dispose();

    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuItemClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientsActionPerformed
        frmclient form = new frmclient();
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuItemClientsActionPerformed

    private void jMenuItemUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemUsersMouseClicked

    }//GEN-LAST:event_jMenuItemUsersMouseClicked

    private void jMenuItemUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsersActionPerformed
        frmuser form = new frmuser(in, out);
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsersActionPerformed

    private void menuBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBaixaActionPerformed

        BaixaForm form = new BaixaForm(in, out);
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuBaixaActionPerformed

    private void menuBaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBaixaMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            out.writeInt(1);
        } catch (IOException ex) {
            Logger.getLogger(frmInici.class.getName()).log(Level.SEVERE, null, ex);
        }
        BaixaForm form = new BaixaForm(in, out);
        form.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_menuBaixaMouseClicked

    private void menuItemReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReserActionPerformed
        frmreservation form = new frmreservation(in, out);
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuItemReserActionPerformed

    private void menuToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuToolsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuToolsActionPerformed

    void logOut(DataInputStream in, DataOutputStream out) {

        try {

            // Llegir la resposta del servidor al establir la connexió
            //String resposta_svr = in.readUTF();
            //Enviem resposta al servidor amb el usuari i la contrasenya
            //out.writeUTF("LOGIN," + getUsuari() + "," + getPass() + "," + getId());
            //Executo la consulta de la crida per sortir
            out.writeInt(0);
            System.out.println("Valor getId: " + getId());

        } catch (IOException ex) {
            Logger.getLogger(frmInici.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem jMenuItemUsers;
    private javax.swing.JMenu menuBaixa;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemClients;
    private javax.swing.JMenuItem menuItemHelp;
    private javax.swing.JMenuItem menuItemPayments;
    private javax.swing.JMenuItem menuItemReser;
    private javax.swing.JMenuItem menuItemRoom;
    private javax.swing.JMenuItem menuItemServices;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuManagement;
    private javax.swing.JMenu menuQueries;
    private javax.swing.JMenu menuReserves;
    private javax.swing.JMenu menuTools;
    // End of variables declaration//GEN-END:variables

}
