/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularis;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utils.SystemUtils;

/**
 *
 * @author Lluís Barbó
 */
public class frmInici extends javax.swing.JFrame {

    static int id;
    static String usuari;
    static String pass;
    static DataInputStream in;
    static DataOutputStream out;
    static int rol;

    public static int getRol() {
        return rol;
    }

    public static void setRol(int rol) {
        frmInici.rol = rol;
    }

    public static DataInputStream getIn() {
        return in;
    }

    public static void setIn(DataInputStream in) {
        frmInici.in = in;
    }

    public static DataOutputStream getOut() {
        return out;
    }

    public static void setOut(DataOutputStream out) {
        frmInici.out = out;
    }

    public static int getId() {
        return id;
    }

    public static void setId(int id) {
        frmInici.id = id;
    }

    public static String getUsuari() {
        return usuari;
    }

    public static void setUsuari(String usuari) {
        frmInici.usuari = usuari;
    }

    public static String getPass() {
        return pass;
    }

    public static void setPass(String pass) {
        frmInici.pass = pass;
    }

    /**
     * Creates new form frmInici
     */
    public frmInici(DataInputStream in, DataOutputStream out, int rol) {
        this.in = in;
        this.out = out;
        this.rol = rol;
        initComponents();
        this.setExtendedState(frmInici.MAXIMIZED_BOTH);
        this.setTitle("Room Reservation System and Sales Management");
        setIconImage(new ImageIcon(getClass().getResource("../images/logoDDL.jpeg")).getImage());
        setLocationRelativeTo(this);
        switch (rol) {
            case 1:
                //Administrator
                JOptionPane.showMessageDialog(this, "You are logged in with the Administrator role");
                menuLogout.setVisible(true);
                menuHelp.setVisible(true);
                menuTools.setVisible(true);
                menuQueries.setVisible(true);
                menuReserves.setVisible(true);
                menuManagement.setVisible(true);
                break;
            case 2:
                //Reception
                JOptionPane.showMessageDialog(this, "You are logged in with the Reception role");
                menuLogout.setVisible(true);
                menuHelp.setVisible(true);
                menuTools.setVisible(false);
                menuQueries.setVisible(false);
                menuReserves.setVisible(true);
                menuManagement.setVisible(true);
                break;
            default:
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuManagement = new javax.swing.JMenu();
        menuItemRoom = new javax.swing.JMenuItem();
        menuItemServices = new javax.swing.JMenuItem();
        menuReserves = new javax.swing.JMenu();
        menuItemReser = new javax.swing.JMenuItem();
        menuItemClients = new javax.swing.JMenuItem();
        menuItemPayments = new javax.swing.JMenuItem();
        menuQueries = new javax.swing.JMenu();
        menuTools = new javax.swing.JMenu();
        jMenuItemUsers = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();
        menuItemHelp = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(144, 164, 174));

        menuBar.setBackground(new java.awt.Color(102, 102, 102));

        menuManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/home-48.png"))); // NOI18N
        menuManagement.setMnemonic('f');
        menuManagement.setText("Management");

        menuItemRoom.setMnemonic('o');
        menuItemRoom.setText("Rooms");
        menuItemRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRoomActionPerformed(evt);
            }
        });
        menuManagement.add(menuItemRoom);

        menuItemServices.setMnemonic('s');
        menuItemServices.setText("Services");
        menuManagement.add(menuItemServices);

        menuBar.add(menuManagement);

        menuReserves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/reserve-48.png"))); // NOI18N
        menuReserves.setMnemonic('e');
        menuReserves.setText("Reserves");

        menuItemReser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReser.setMnemonic('t');
        menuItemReser.setText("Reservations and services");
        menuItemReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReserActionPerformed(evt);
            }
        });
        menuReserves.add(menuItemReser);

        menuItemClients.setMnemonic('y');
        menuItemClients.setText("Clients");
        menuItemClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientsActionPerformed(evt);
            }
        });
        menuReserves.add(menuItemClients);

        menuItemPayments.setMnemonic('p');
        menuItemPayments.setText("Payments");
        menuReserves.add(menuItemPayments);

        menuBar.add(menuReserves);

        menuQueries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/resume-48.png"))); // NOI18N
        menuQueries.setMnemonic('h');
        menuQueries.setText("Queries");
        menuBar.add(menuQueries);

        menuTools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/tools-48.png"))); // NOI18N
        menuTools.setText("Tools");

        jMenuItemUsers.setText("Users and access");
        jMenuItemUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsersActionPerformed(evt);
            }
        });
        menuTools.add(jMenuItemUsers);

        menuBar.add(menuTools);

        menuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/help-48.png"))); // NOI18N
        menuHelp.setText("Help");

        menuItemAbout.setText("About");
        menuHelp.add(menuItemAbout);

        menuItemHelp.setText("Help");
        menuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHelpActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemHelp);

        menuBar.add(menuHelp);

        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formularis/logout-rounded-left-48.png"))); // NOI18N
        menuLogout.setText("LogOut");
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        menuBar.add(menuLogout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        frmlogin form = new frmlogin();
        form.setVisible(true);
        logOut(in, out);
        this.dispose();

    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuItemClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientsActionPerformed
        frmclient form = new frmclient(in, out);
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuItemClientsActionPerformed

    private void jMenuItemUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsersActionPerformed
        frmuser form = new frmuser(in, out);
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsersActionPerformed

    private void menuItemReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReserActionPerformed
        frmreservation form = new frmreservation(in, out);
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuItemReserActionPerformed

    private void menuItemRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRoomActionPerformed
        frmrooms form = new frmrooms(in, out);
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_menuItemRoomActionPerformed

    private void menuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHelpActionPerformed
        frmhelp form = new frmhelp(in, out);
        desktop.add(form);
        form.toFront();
        form.setVisible(true);
        
    }//GEN-LAST:event_menuItemHelpActionPerformed

    void logOut(DataInputStream in, DataOutputStream out) {

        try {
            /*
            //Cálcul clau pública client
            String[] claus_ps = SystemUtils.clauPublicaClient().split(",");
            //Enviem la clau pública del client al servidor
            out.writeUTF(String.valueOf(claus_ps[0]));
            //llegim la clau pública del servidor
            BigInteger shared_secret = SystemUtils.calculClauCompartida(in.readUTF(), claus_ps[1]);
            //Executo la consulta de la crida per sortir
            int exit = 0;
            out.writeUTF(SystemUtils.encryptedText("0", shared_secret.toByteArray()));  */
            out.writeInt(0);
            System.out.println("Valor getId: " + getId());

        } catch (IOException ex) {
            Logger.getLogger(frmInici.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem jMenuItemUsers;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemClients;
    private javax.swing.JMenuItem menuItemHelp;
    private javax.swing.JMenuItem menuItemPayments;
    private javax.swing.JMenuItem menuItemReser;
    private javax.swing.JMenuItem menuItemRoom;
    private javax.swing.JMenuItem menuItemServices;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuManagement;
    private javax.swing.JMenu menuQueries;
    private javax.swing.JMenu menuReserves;
    private javax.swing.JMenu menuTools;
    // End of variables declaration//GEN-END:variables

}
